// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBc3rsQyYL1cgXDxH8h1D787VFLtruM6c',
    appId: '1:976528411320:web:70902e8902dd8fa93d824d',
    messagingSenderId: '976528411320',
    projectId: 'luxury-moonseadb',
    authDomain: 'luxury-moonseadb.firebaseapp.com',
    storageBucket: 'luxury-moonseadb.firebasestorage.app',
    measurementId: 'G-7700JWDVZG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNRA26yZhsaoYqTUEPR8ACfVQhVUKypUc',
    appId: '1:976528411320:android:26db02deab7f4b453d824d',
    messagingSenderId: '976528411320',
    projectId: 'luxury-moonseadb',
    storageBucket: 'luxury-moonseadb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9gTKAf6ZBFhBOcSlXevNWril5-ojESv4',
    appId: '1:976528411320:ios:355c1d379b550dad3d824d',
    messagingSenderId: '976528411320',
    projectId: 'luxury-moonseadb',
    storageBucket: 'luxury-moonseadb.firebasestorage.app',
    iosBundleId: 'com.example.hotel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9gTKAf6ZBFhBOcSlXevNWril5-ojESv4',
    appId: '1:976528411320:ios:355c1d379b550dad3d824d',
    messagingSenderId: '976528411320',
    projectId: 'luxury-moonseadb',
    storageBucket: 'luxury-moonseadb.firebasestorage.app',
    iosBundleId: 'com.example.hotel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBc3rsQyYL1cgXDxH8h1D787VFLtruM6c',
    appId: '1:976528411320:web:bc1ddc2af155c3173d824d',
    messagingSenderId: '976528411320',
    projectId: 'luxury-moonseadb',
    authDomain: 'luxury-moonseadb.firebaseapp.com',
    storageBucket: 'luxury-moonseadb.firebasestorage.app',
    measurementId: 'G-HC83V5SCST',
  );
}
